export {default as App} from './app'
export {default as Login} from './login'
export {default as Header} from './header'
export {default as Home} from './home'
export {default as Search} from './search'
export {default as Register} from './register'
export {default as Myshoes} from './myshoes'